#! /bin/bash
set -e

source /etc/profile.d/rbenv.sh
source /opt/build-config

INSTALL_DIR=${INSTALL_DIR:-/home/kandan}
RUN_USER=${RUN_USER:-kandan}

LOG_DIR="/var/log/kandan"
KANDAN_CONF=/etc/supervisor/conf.d/kandan.conf

# add user
useradd -d ${INSTALL_DIR} -m ${RUN_USER}

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install \
  supervisor \
  build-essential \
  curl \
  unzip \
  git-core \
  gcc \
  g++ \
  make

# install dependency
apt-get -y install \
  libpq5 sqlite3 libmysqlclient18 \
  libcurl3 libcurl3-nss libpcre3 libxml2 libxslt1.1 \
  libreadline5 libyaml-0-2\
  libmysqlclient-dev libsqlite3-dev libpq-dev \
  libcurl4-openssl-dev libpcre3-dev libxml2-dev libxslt-dev \
  libreadline-gplv2-dev

# move supervisord.log file to ${LOG_DIR}
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# populate ${LOG_DIR}
if [ ! -d ${LOG_DIR} ]; then
  mkdir -p -m 755 ${LOG_DIR}
fi

# populate ${KANDAN_CONF}
cat > ${KANDAN_CONF} <<__EOL__
[program:kandan]
command=/opt/rbenv/shims/bundle exec thin start -e production
command=${INSTALL_DIR}/bin/kandan
autostart=true
autorestart=false
username=${RUN_USER}
directory=${INSTALL_DIR}
stdout_logfile=${LOG_DIR}/%(program_name)s.log
stderr_logfile=${LOG_DIR}/%(program_name)s.log
environment=RBENV_ROOT=/opt/rbenv
__EOL__

# install
cd ${INSTALL_DIR}
git clone https://github.com/miurahr/kandan.git
cd kandan
git checkout i18n

gem install execjs
gem install guard
gem install mysql2 # force install for mysql
bundle install --without development,test

sed -ri 's/config.serve_static_assets = false/config.serve_static_assets = true/g' ${INSTALL_DIR}/kandan/config/environments/production.rb

chown -R kandan:kandan ${INSTALL_DIR}/kandan

# cleanup dev files
apt-get -y remove \
  libmysqlclient-dev libsqlite3-dev libpq-dev \
  libcurl4-openssl-dev libpcre3-dev libxml2-dev libxslt-dev \
  libreadline-gplv2-dev

# clean apt caches, build dependency
apt-get clean
apt-get -y autoremove
find /var/lib/apt/lists/ -type f -exec rm -f {} \;
