#!/bin/bash
set -e

. /etc/profile.d/rbenv.sh
BUNDLE=`which bundle`

INSTALL_DIR=${INSTALL_DIR:-/home/kandan}

# add user
useradd -d ${INSTALL_DIR} -m kandan

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install \
  supervisor \
  build-essential \
  curl \
  unzip \
  git-core \
  gcc \
  g++ \
  make

# install dependency
curl -sL https://deb.nodesource.com/setup | bash -
apt-get -y install nodejs \
  libpq5 sqlite3 libmysqlclient18 \
  libcurl3 libcurl3-nss libpcre3 libxml2 libxslt1.1 \
  libreadline5 libyaml-0-2\
  libmysqlclient-dev libsqlite3-dev libpq-dev \
  libcurl4-openssl-dev libpcre3-dev libxml2-dev libxslt-dev \
  libreadline-gplv2-dev
npm install -g npm

# install
cd ${INSTALL_DIR}
git clone https://github.com/miurahr/kandan.git
cd kandan

gem install execjs
bundle install

cat > ${INSTALL_DIR}/kandan/config/database.yml << __EOL__
development:
  adapter: sqlite3
  database: kandan.sqlite
__EOL__

chown -R kandan:kandan ${INSTALL_DIR}/kandan

cd ${INSTALL_DIR}/kandan
sudo -u kandan ${BUNDLE} exec rake db:create db:migrate kandan:bootstrap RAILS_ENV=development
sudo -u kandan ${BUNDLE} exec rake assets:precompile RAILS_ENV=development
sudo -u kandan ${BUNDLE} exec rake kandan:boot_hubot RAILS_ENV=development
sudo -u kandan ${BUNDLE} exec rake kandan:hubot_access_key RAILS_ENV=development | grep -oP "(?<=Your hubot access key is )[^ ]*" > hubot-key

# clean apt caches, build dependency
apt-get clean
